---

- hosts: all
  become: true
  pre_tasks:

  - name: DPKG in Ubuntu Server
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Update in Ubuntu Server
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install epel-release and dnf
    dnf:
      name:
        - epel-release
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Update CentOS Server
    dnf:
      update_cache: yes
      name: "*"
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: ubuntu
  become: true
  roles:
    - ubuntu

- hosts: centos
  become: true
  roles:
    - centos
